repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        files: \.py$
    -   id: trailing-whitespace
        files: \.py$
    -   id: check-ast
        files: \.py$
    -   id: check-builtin-literals
        files: \.py$
    -   id: check-docstring-first
        files: \.py$
    -   id: check-case-conflict
        files: \.py$
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: ^venv/
-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        exclude: ^venv/
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--ignore=W503,W504,E302,E203']
        exclude: ^(venv)/.*
